# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idearequest",
            name="model_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ollama model (e.g. llama3, gpt-oss:20b) or OpenAI model",
                max_length=100,
            ),
        ),
    ]
