# Generated by Django 5.2.11 on 2026-02-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_idearequest_model_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="role",
            field=models.CharField(
                choices=[
                    ("orchestrator", "Orchestrator"),
                    ("internet_explorer", "Internet Explorer"),
                    ("idea_generator", "Idea Generator"),
                    ("estimator", "Estimator"),
                    ("executor", "Executor"),
                    ("critic", "Critic"),
                    ("overviewer", "Overviewer"),
                    ("evaluator", "Evaluator"),
                    ("prompt_generator", "Prompt Generator"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="idearequest",
            name="model_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ollama model (e.g. gpt-oss:20b, qwen3) or OpenAI model; Ollama requires tool-capable model",
                max_length=100,
            ),
        ),
    ]
