# Generated by Django 4.2.26 on 2026-02-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_company_companyagent_directordiscussion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directordiscussion",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("AWAITING_SELECTION", "Awaiting Selection"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="ACTIVE",
                max_length=30,
            ),
        ),
    ]
