# Generated by Django 4.2.26 on 2026-02-21 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0005_add_discussion_failed_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCalendarAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_date", models.DateField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("DEFERRED", "Deferred"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("completion_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_entries",
                        to="ideas.actionproposal",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_actions",
                        to="ideas.company",
                    ),
                ),
            ],
            options={"ordering": ["action_date", "title"],},
        ),
    ]
