# Generated by Django 4.2.26 on 2026-02-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0006_add_company_calendar_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="directordiscussion",
            name="cancelled",
            field=models.BooleanField(
                default=False,
                help_text="When True, running discussion process will exit on next check",
            ),
        ),
    ]
