# Generated by Django 4.2.26 on 2026-02-23 20:33

from django.db import migrations, models


def migrate_custom_to_operations(apps, schema_editor):
    CompanyAgent = apps.get_model("ideas", "CompanyAgent")
    CompanyAgent.objects.filter(role="custom").update(role="operations")


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0007_add_discussion_cancelled"),
    ]

    operations = [
        migrations.RunPython(migrate_custom_to_operations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZING", "Initializing"),
                    ("ACTIVE", "Active"),
                    ("REGENERATING_AGENTS", "Regenerating Agents"),
                    ("COMPLETED", "Completed"),
                ],
                default="INITIALIZING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="companyagent",
            name="role",
            field=models.CharField(
                choices=[
                    ("cpa", "CPA (Budget & Finance)"),
                    ("director", "Director"),
                    ("marketer", "Marketer"),
                    ("developer", "Developer"),
                    ("product", "Product Manager"),
                    ("operations", "Operations"),
                ],
                max_length=30,
            ),
        ),
    ]
