# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0008_remove_custom_role_add_regenerating"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="autonomous_mode",
            field=models.BooleanField(
                default=True,
                help_text="When True, agents select plans, schedule, execute, and improve without user action",
            ),
        ),
    ]
