"""URL configuration for web app."""
from django.urls import path

from . import (
    auth_views,
    company_planning_views,
    google_calendar_views,
    llm_settings_views,
    task_views,
    user_views,
    views,
)

urlpatterns = [
    path("login/", auth_views.app_login, name="app_login"),
    path("logout/", auth_views.app_logout, name="app_logout"),
    path(
        "password-change-required/",
        auth_views.force_password_change,
        name="force_password_change",
    ),
    path("settings/llm/", llm_settings_views.llm_settings, name="llm_settings"),
    path("settings/llm/test/", llm_settings_views.llm_settings_test, name="llm_settings_test"),
    path(
        "settings/google-calendar/",
        google_calendar_views.google_calendar_settings,
        name="google_calendar_settings",
    ),
    path(
        "settings/google-calendar/connect/",
        google_calendar_views.google_calendar_connect,
        name="google_calendar_connect",
    ),
    path(
        "settings/google-calendar/callback/",
        google_calendar_views.google_calendar_callback,
        name="google_calendar_callback",
    ),
    path(
        "settings/google-calendar/disconnect/",
        google_calendar_views.google_calendar_disconnect,
        name="google_calendar_disconnect",
    ),
    path(
        "settings/google-calendar/sync-existing/",
        google_calendar_views.google_calendar_sync_existing,
        name="google_calendar_sync_existing",
    ),
    path("settings/users/", user_views.user_list, name="user_list"),
    path("settings/users/new/", user_views.user_create, name="user_create"),
    path("settings/users/<int:user_id>/edit/", user_views.user_edit, name="user_edit"),
    path("", views.home, name="home"),
    path("ideas/new/", views.new_idea, name="new_idea"),
    path("ideas/<uuid:pk>/", views.idea_detail, name="idea_detail"),
    path("ideas/<uuid:pk>/attachments/", views.add_idea_attachment, name="add_idea_attachment"),
    path("ideas/<uuid:pk>/status/", views.idea_status, name="idea_status"),
    path("ideas/<uuid:pk>/accept/", views.accept_idea, name="accept_idea"),
    path("ideas/<uuid:pk>/stop/", views.stop_pipeline, name="stop_pipeline"),
    path("ideas/<uuid:pk>/rerun/", views.rerun_failed_steps, name="rerun_failed"),
    path("ideas/<uuid:pk>/rerun-from-scratch/", views.rerun_from_scratch, name="rerun_from_scratch"),
    path("ideas/<uuid:pk>/delete/", views.delete_idea_confirm, name="delete_idea_confirm"),
    path("ideas/<uuid:pk>/delete/confirm/", views.delete_idea, name="delete_idea"),
    path("ideas/<uuid:pk>/save-conclusion/", views.save_conclusion, name="save_conclusion"),
    path("ideas/<uuid:pk>/download/", views.download_json, name="download_json"),
    path("my-tasks/", task_views.my_tasks, name="my_tasks"),
    path("companies/", views.company_list, name="company_list"),
    path("companies/<uuid:pk>/", views.company_detail, name="company_detail"),
    path("companies/<uuid:pk>/team/add/", views.add_team_member, name="add_team_member"),
    path("companies/<uuid:pk>/toggle-autonomous/", views.toggle_autonomous_mode, name="toggle_autonomous_mode"),
    path("companies/<uuid:pk>/run-autonomous-loop/", views.run_autonomous_loop_now, name="run_autonomous_loop_now"),
    path("companies/<uuid:pk>/regenerate-agents/", views.regenerate_agents, name="regenerate_agents"),
    path("companies/<uuid:pk>/status/", views.company_status, name="company_status"),
    path("companies/<uuid:company_pk>/agents/<uuid:agent_pk>/chat/", views.company_agent_chat, name="company_agent_chat"),
    path("companies/<uuid:company_pk>/agents/<uuid:agent_pk>/chat/send/", views.agent_chat_send, name="agent_chat_send"),
    path(
        "companies/<uuid:company_pk>/agents/<uuid:agent_pk>/chat/messages/<uuid:message_pk>/status/",
        views.agent_chat_message_status,
        name="agent_chat_message_status",
    ),
    path("companies/<uuid:company_pk>/discussions/new/", views.start_discussion, name="start_discussion"),
    path("companies/<uuid:company_pk>/discussions/<uuid:discussion_pk>/", views.director_discussion_detail, name="director_discussion_detail"),
    path("companies/<uuid:company_pk>/discussions/<uuid:discussion_pk>/rerun/", views.rerun_discussion, name="rerun_discussion"),
    path("companies/<uuid:company_pk>/discussions/<uuid:discussion_pk>/status/", views.discussion_status, name="discussion_status"),
    path("companies/<uuid:company_pk>/actions/<uuid:action_pk>/select/", views.action_select, name="action_select"),
    path("companies/<uuid:company_pk>/actions/<uuid:action_pk>/schedule/", views.action_schedule, name="action_schedule"),
    path("companies/<uuid:company_pk>/actions/<uuid:action_pk>/reject/", views.action_reject, name="action_reject"),
    path("companies/<uuid:company_pk>/calendar/", views.company_calendar, name="company_calendar"),
    path(
        "companies/<uuid:company_pk>/calendar/optimize/",
        views.company_calendar_optimize,
        name="company_calendar_optimize",
    ),
    path("companies/<uuid:company_pk>/calendar/add/", views.calendar_action_add, name="calendar_action_add"),
    path("companies/<uuid:company_pk>/calendar/<int:year>/<int:month>/<int:day>/", views.company_calendar_date, name="company_calendar_date"),
    path("companies/<uuid:company_pk>/calendar/entry/<uuid:entry_pk>/status/", views.calendar_action_update_status, name="calendar_action_update_status"),
    path("companies/<uuid:company_pk>/tasks/", company_planning_views.company_tasks, name="company_tasks"),
    path(
        "companies/<uuid:company_pk>/tasks/run/",
        company_planning_views.company_tasks_run_now,
        name="company_tasks_run_now",
    ),
    path(
        "companies/<uuid:company_pk>/tasks/<uuid:task_pk>/",
        company_planning_views.company_task_detail,
        name="company_task_detail",
    ),
    path(
        "companies/<uuid:company_pk>/tasks/<uuid:task_pk>/escalate/",
        company_planning_views.company_task_escalate,
        name="company_task_escalate",
    ),
    path("companies/<uuid:company_pk>/planning/", company_planning_views.company_planning, name="company_planning"),
    path(
        "companies/<uuid:company_pk>/planning/start/",
        company_planning_views.company_planning_start,
        name="company_planning_start",
    ),
    path(
        "companies/<uuid:company_pk>/planning/<uuid:session_pk>/",
        company_planning_views.company_planning_detail,
        name="company_planning_detail",
    ),
    path(
        "companies/<uuid:company_pk>/planning/<uuid:session_pk>/status/",
        company_planning_views.planning_session_status,
        name="planning_session_status",
    ),
    path("companies/<uuid:company_pk>/direction/", company_planning_views.company_direction, name="company_direction"),
    path("companies/<uuid:company_pk>/history/", company_planning_views.company_history, name="company_history"),
]
